apiVersion: v1
entries:
  geopulse:
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2025-11-25T10:52:19.296264074Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: f9538efbcf85669011d2ef614e1fd146e171e75e189a24198a1ac3aa6f3ff156
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2025-11-25T10:52:19.295169967Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 3c3371894d512fab97db87c3e397b874a9942c613a169a248774927141e90857
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2025-11-25T10:52:19.293577193Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 00ac187ca9f870a35265a90d90ef10132485bbf35a8a8e64f658c9be73ad618b
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.2.3
    created: "2025-11-25T10:52:19.292277113Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: f105f38163321c6b091d7e7b0c8c3f4d1946f3015977fe45906d1a9756b5f3a7
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v2
    appVersion: 1.2.2
    created: "2025-11-25T10:52:19.291194658Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 2c456af48060807a34112e91e6e512ba329b76b0b849e48ce020cf741a31d1a4
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2025-11-25T10:52:19.290038335Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: b8acab499d64209062049ca03f10a2ccb177e3e1610f8ffcb18f5c31c3e4eea9
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2025-11-25T10:52:19.288925183Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 9163b40a24bcbcf3749e4d8a71691abee673fb8774426d5f06903a1d386063f1
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.3
    created: "2025-11-25T10:52:19.287787355Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: e0c9971a43d5ee8d3527927e8d00fd701ce93054c1b7287b9ae0f7380b95cc97
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2025-11-25T10:52:19.285606436Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: fba5326acfcf8362f4d929cfcd7e4828e506a611b6248345f39a22e9ecb241f0
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.1.2.tgz
    version: 1.1.2
generated: "2025-11-25T10:52:19.284339456Z"
