apiVersion: v1
entries:
  geopulse:
  - apiVersion: v2
    appVersion: 1.13.0
    created: "2026-01-13T16:58:50.077735515Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 8999861cc0d4cc699bdbf23e3eb4e498bbd4db7e4343a09bdf059a8e09bc85a1
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.13.0.tgz
    version: 1.13.0
  - apiVersion: v2
    appVersion: 1.12.0
    created: "2026-01-13T16:58:50.076340015Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: a8308bdf4391884b6af39f3933d0a56715a853d7768bdaba31616d2313c3608a
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.12.0.tgz
    version: 1.12.0
  - apiVersion: v2
    appVersion: 1.11.0
    created: "2026-01-13T16:58:50.074963Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: c07797057beb17cbb37f40cc225d21af89d24deb81605eecc7464933b7b128fc
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.11.0.tgz
    version: 1.11.0
  - apiVersion: v2
    appVersion: 1.10.2
    created: "2026-01-13T16:58:50.073605751Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 9a8cd3c7d6d2f11acd415e9ee7b6aefe0f04137b234f14f88aba4ee25e8a9c83
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.10.2.tgz
    version: 1.10.2
  - apiVersion: v2
    appVersion: 1.10.1
    created: "2026-01-13T16:58:50.072169996Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 012909d98146e9ff570c0cd02b2c8a665c62e8b45675ba2619ccd2f1c52c2408
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.10.1.tgz
    version: 1.10.1
  - apiVersion: v2
    appVersion: 1.10.0
    created: "2026-01-13T16:58:50.069882437Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: dbc7cc7264b5f28ff59ad6d209657944f24b15bf5d15f2c5e92eaad2bd64d661
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.10.0.tgz
    version: 1.10.0
  - apiVersion: v2
    appVersion: 1.9.1
    created: "2026-01-13T16:58:50.096663538Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 0ce4652280a0177c6245afbf76fd2ba8da5772dadff4da296a74a59f922e24f7
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.9.1.tgz
    version: 1.9.1
  - apiVersion: v2
    appVersion: 1.9.0
    created: "2026-01-13T16:58:50.095295299Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 5b800c3ec0f81fcee8b9eceeb98b15e3c389a5f1c5a47d4d76470fb049bba543
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.9.0.tgz
    version: 1.9.0
  - apiVersion: v2
    appVersion: 1.8.1
    created: "2026-01-13T16:58:50.092930758Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 6ef4fc9b0fbec9372b691a117edf56f45a0522944da202eb2be873d76689fefc
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.8.1.tgz
    version: 1.8.1
  - apiVersion: v2
    appVersion: 1.8.0
    created: "2026-01-13T16:58:50.091606942Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 0e9a8f39167774d6cdf0888a5ef7520eb8d88c8b214704d9381a3a7382a02793
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.8.0.tgz
    version: 1.8.0
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2026-01-13T16:58:50.090243292Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 84134d36b1cec4c2137fa79135867355809af519a1a031fc50a3c99cf6a784d3
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.7.0.tgz
    version: 1.7.0
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2026-01-13T16:58:50.088907283Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: f9538efbcf85669011d2ef614e1fd146e171e75e189a24198a1ac3aa6f3ff156
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.6.0.tgz
    version: 1.6.0
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2026-01-13T16:58:50.087755328Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 4950b58c87cf5ff88681b04d46d39e074ac29b3064b747f53868256843cc1198
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.5.0.tgz
    version: 1.5.0
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2026-01-13T16:58:50.085906097Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 3c3371894d512fab97db87c3e397b874a9942c613a169a248774927141e90857
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.4.0.tgz
    version: 1.4.0
  - apiVersion: v2
    appVersion: 1.3.0
    created: "2026-01-13T16:58:50.084601107Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 00ac187ca9f870a35265a90d90ef10132485bbf35a8a8e64f658c9be73ad618b
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.3.0.tgz
    version: 1.3.0
  - apiVersion: v2
    appVersion: 1.2.3
    created: "2026-01-13T16:58:50.083493345Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: f105f38163321c6b091d7e7b0c8c3f4d1946f3015977fe45906d1a9756b5f3a7
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.3.tgz
    version: 1.2.3
  - apiVersion: v2
    appVersion: 1.2.2
    created: "2026-01-13T16:58:50.082369623Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 2c456af48060807a34112e91e6e512ba329b76b0b849e48ce020cf741a31d1a4
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.2.tgz
    version: 1.2.2
  - apiVersion: v2
    appVersion: 1.2.1
    created: "2026-01-13T16:58:50.081186941Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: b8acab499d64209062049ca03f10a2ccb177e3e1610f8ffcb18f5c31c3e4eea9
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.1.tgz
    version: 1.2.1
  - apiVersion: v2
    appVersion: 1.2.0
    created: "2026-01-13T16:58:50.08000515Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: 9163b40a24bcbcf3749e4d8a71691abee673fb8774426d5f06903a1d386063f1
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.2.0.tgz
    version: 1.2.0
  - apiVersion: v2
    appVersion: 1.1.3
    created: "2026-01-13T16:58:50.068468472Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: e0c9971a43d5ee8d3527927e8d00fd701ce93054c1b7287b9ae0f7380b95cc97
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.1.3.tgz
    version: 1.1.3
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2026-01-13T16:58:50.067209067Z"
    description: A self-hosted location tracking and analysis platform with PostGIS
      and optional MQTT support
    digest: fba5326acfcf8362f4d929cfcd7e4828e506a611b6248345f39a22e9ecb241f0
    home: https://github.com/tess1o/geopulse
    icon: https://raw.githubusercontent.com/tess1o/geopulse/main/frontend/public/geopulse-logo.svg
    keywords:
    - gps
    - tracking
    - location
    - postgis
    - mqtt
    - self-hosted
    maintainers:
    - email: support@geopulse.io
      name: GeoPulse Team
    name: geopulse
    sources:
    - https://github.com/tess1o/geopulse
    type: application
    urls:
    - https://tess1o.github.io/geopulse/charts/geopulse-1.1.2.tgz
    version: 1.1.2
generated: "2026-01-13T16:58:50.065851378Z"
